/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorfulText: typeof import('./src/components/ui/ColorfulText.vue')['default']
    copy: typeof import('./src/components/Mine/index copy.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    GameLog: typeof import('./src/components/GameLog/index.vue')['default']
    GameLogs: typeof import('./src/components/InfoView/GameLogs.vue')['default']
    GameLogs1: typeof import('./src/components/InfoView/GameLogs1.vue')['default']
    Head: typeof import('./src/components/head.vue')['default']
    InfoView: typeof import('./src/components/InfoView/index.vue')['default']
    ItemProgress: typeof import('./src/components/InfoView/ItemProgress.vue')['default']
    LogsView: typeof import('./src/components/LogsView/index.vue')['default']
    MapView: typeof import('./src/components/MapView/index.vue')['default']
    Mine: typeof import('./src/components/Mine/index.vue')['default']
    Miner: typeof import('./src/components/Miner/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDiv: typeof import('naive-ui')['NDiv']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLog: typeof import('naive-ui')['NLog']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSplit: typeof import('naive-ui')['NSplit']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    PackItem: typeof import('./src/components/ui/PackItem.vue')['default']
    RarityText: typeof import('./src/components/ui/RarityText.vue')['default']
    Status: typeof import('./src/components/Status/index.vue')['default']
  }
}
